version: "3"
services:
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "supersecret"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - fs:/var/lib/minio

  postgres:
    image: postgres:14.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env

  cache:
    image: redis:6.0-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  fs:
    driver: local
  cache:
    driver: local
