version: "3"
services:
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "supersecret"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - fs:/var/lib/minio

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "bealy"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pasword"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

  cache:
    image: redis:7.2.3
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redispassword
    volumes:
      - cache:/data

volumes:
  my-db:
    driver: local
  fs:
    driver: local
  cache:
    driver: local
