version: "3"
services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "supersecret"
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - fs:/var/lib/minio

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "bealy"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "pasword"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
    driver: local
  fs:
    driver: local
